Modify README part: Build, VS Code
xnth97/TJUThesisLatexTemplate pull request #6
Opened 2021-01-05 05:51 UTC by geniusLcy

## 编译
仅使用 `xelatex tjumain.tex` 编译不会生成目录、引用标号等，推荐README告诉大家直接xe->bib->xe->xe全家桶编译
```bash
xelatex tjumain.tex
bibtex tjumain.tex
xelatex tjumain.tex
xelatex tjumain.tex
```
## VS Code
时至今日LaTeX Workshop以趋于完善，配置方面也发生了一些微小的改动。于README中修改过时的配置，提供目前为止较为推荐的配置
> It works on my machine!

## 感谢学长、前辈们的无私付出！

2021-01-05 06:03 UTC, geniusLcy commented
## 顺便贴出我个人的VS Code中LaTeX部分的全部配置文件
```json
// =============================== LaTeX BEGIN ========================================
    "latex-workshop.latex.autoBuild.run": "never",
    "latex-workshop.message.error.show": false,
    "latex-workshop.message.warning.show": false,

    "latex-workshop.latex.tools": [
        {
            "name": "xelatex",
            "command": "xelatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOCFILE%"
            ]
        },
        {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOCFILE%"
            ]
        },
        {
            "name": "bibtex",
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ]
        }
    ],

    "latex-workshop.latex.recipes": [
        {
            "name": "xelatex",
            "tools": [
                "xelatex"
            ],
        },
        {
            "name": "pdflatex",
            "tools": [
                "pdflatex"
            ]
        },
        {
            "name": "xe->bib->xe->xe",
            "tools": [
                "xelatex",
                "bibtex",
                "xelatex",
                "xelatex"
            ]
        },
        {
            "name": "pdf->bib->pdf->pdf",
            "tools": [
                "pdflatex",
                "bibtex",
                "pdflatex",
                "pdflatex"
            ]
        }
    ],
    "latex-workshop.view.pdf.viewer": "external",

    // 下面为配置vscode与SumatraPDF的关联和反向搜索: 记得替换...处的语句为自己的路径!
    "latex-workshop.view.pdf.external.viewer.command": "C:/.../SumatraPDF.exe",
    "latex-workshop.view.pdf.external.viewer.args": [
        "-forward-search",
        "%TEX%",
        "%LINE%",
        "-reuse-instance",
        "-inverse-search",
        "\"C:/.../Microsoft VS Code/Code.exe\" \"C:/.../Microsoft VS Code/resources/app/out/cli.js\" -gr \"%f\":\"%l\"",
    "%PDF%"
    ],

    "latex-workshop.view.pdf.external.synctex.command": "C:/.../SumatraPDF.exe",
    "latex-workshop.view.pdf.external.synctex.args": [
        "-forward-search",
        "%TEX%",
        "%LINE%",
        "-reuse-instance",
        "-inverse-search",
        "\"C:/.../Microsoft VS Code/Code.exe\" \"C:/.../Microsoft VS Code/resources/app/out/cli.js\" -gr \"%f\":\"%l\"",
    "%PDF%"
    ],
    "latex-workshop.latex.clean.fileTypes": [
        "*.aux",
        "*.bbl",
        "*.blg",
        "*.idx",
        "*.ind",
        "*.lof",
        "*.lot",
        "*.out",
        "*.toc",
        "*.acn",
        "*.acr",
        "*.alg",
        "*.glg",
        "*.glo",
        "*.gls",
        "*.ist",
        "*.fls",
        "*.log",
        "*.fdb_latexmk",
        "*.bcf",
        "*.run.xml",
        "*.synctex.gz"
    ],
    // =============================== LaTeX END ===========================================
```

2021-01-06 01:17 UTC, xnth97 requested changes
LGTM

2021-01-06 01:17 UTC, xnth97 commented on README.md
> +            "%DOCFILE%" // 将%DOC%替换成%DOCFILE%可以支持编译中文路径下的文件
添加注释的话请把172行 json 改成 js 以避免 github markdown 报错

2021-01-06 01:17 UTC, xnth97 commented on README.md
> +    * Windows: TeX Live (千万别碰邪恶CTeX啊啊啊!!!)
hhh 不建议加入个人吐槽

2021-01-06 01:17 UTC, xnth97 commented on README.md
> +新增：适用于texlive 2020，使用 `xelatex->bibtex->xelatex->xelatex` 编译链。在 Windows 10 下进行修改与测试正常。
建议直接修改111行说明

2021-01-06 04:36 UTC, geniusLcy commented
感谢review😄

2021-01-06 04:46 UTC, merged